### ISSUE TITLE
It is not able to decrypt file which are encrypted by rclone. 

### ISSUE THREAD

**Issue by firefoxOnFire** [Ftbom/rclone_crypt_py#1]
I have rclone encrypted file. And when I use this code to decrypt, it shows error.
Any way to use this to decrypt rclone encrypted file??

**Comment by Ftbom** [comment]
can you show me your code and the error?

**Comment by Ftbom** [comment]
To decrypt a file:

```python
from rclone import Crypt
crypt = Crypt('passwd1', 'passwd2')
crypt.File.file_decrypt('encrypted_file.bin', 'new_decrypted_file')
```
And you should note that the 'passwd1' and 'passwd2' is **not the strings in rclone config file**. You should use the passwd when you create the rclone crypt storage

**Comment by Ftbom** [comment]
yes, i'll add this function in the future.

**Comment by Ftbom** [comment]
Now you can use passwords in configuration file directly.

```python
crypt = Crypt(passwd1, passwd2, passwd_obscured = True)
```
