### ISSUE TITLE
文件名加密可以支持base64编码吗

### ISSUE THREAD

**Issue by caly5144** [Ftbom/rclone_crypt_py#4]
作者您好，我看name_cipher.py中对文件名加密使用的是base32编码，请问是否可以支持base64？

**Comment by Ftbom** [comment]
[rclone crypt储存](https://rclone.org/crypt/)文件名加密用的就是base32编码，这是为了对rclone crypt做适配

**Comment by Ftbom** [comment]
才了解到Rclone文件名加密还支持base64，现在已经添加base64支持
